source 'https://rubygems.org'
ruby '2.5.1'
gem 'jekyll', group: :jekyll_plugins
gem 'git'
gem 'rspec'  
gem 'sinatra'  
gem 'thin'
gem 'rack'  
gem 'rack-test'
gem 'guard'  
gem 'guard-rspec'  
gem 'foreman' 
gem 'rubyzip'